// <auto-generated />
using System;
using InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609220515_AddIsFavoriteToProduct")]
    partial class AddIsFavoriteToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InventoryManagement.Data.Models.CashTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CashAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCash")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCrates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCrates");

                    b.ToTable("cashTransactions");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Crates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Crates");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefCustomer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marques");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Nature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Natures");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PaymentCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePayment")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCrates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberPayment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Payment")
                        .IsRequired()
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCrates");

                    b.HasIndex("IdCustomer");

                    b.ToTable("paymentCustomers");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PaymentVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePayment")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCrates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVendor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberPayment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Payment")
                        .IsRequired()
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCrates");

                    b.HasIndex("IdVendor");

                    b.ToTable("paymentVendors");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PriceLists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Colisage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MarqueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NatureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QtyAlert")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefProduct")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalesPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StockQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taxe")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MarqueId");

                    b.HasIndex("NatureId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BalancePurchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePurchase")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCrates")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdVendor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberPurchase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaymentPurchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalPurchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalWithoutTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalWithoutTaxRemise")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCrates");

                    b.HasIndex("IdVendor");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PurchaseLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProduct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPurchase")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefProduct")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Taxe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWithoutTax")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdPurchase");

                    b.ToTable("purchaseLines");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GapTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("IdCrates")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdVendor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberReturn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalPurchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalReturn")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCrates");

                    b.HasIndex("IdVendor");

                    b.ToTable("returnPurchases");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnPurchaseLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdReturnSales")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefProduct")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Taxe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWithoutTax")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdReturnSales");

                    b.ToTable("returnPurchaseLines");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GapTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("IdCrates")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberReturn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalInvoice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalReturn")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCrates");

                    b.HasIndex("IdCustomer");

                    b.ToTable("returnSales");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnSalesLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdReturnSales")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefProduct")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Taxe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWithoutTax")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdReturnSales");

                    b.ToTable("returnSalesLines");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.SalesInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProduct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSalesInvoice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefProduct")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Taxe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWithoutTax")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSalesInvoice");

                    b.ToTable("salesInvoiceLines");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.SalesInvoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BalanceInvoice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInvoice")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCrates")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberInvoice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaymentInvoice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalInvoice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalWithoutTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalWithoutTaxRemise")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCrates");

                    b.HasIndex("IdCustomer");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeleterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefVendor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.CashTransaction", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Crates", "Crates")
                        .WithMany()
                        .HasForeignKey("IdCrates");

                    b.Navigation("Crates");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PaymentCustomer", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Crates", "Crates")
                        .WithMany()
                        .HasForeignKey("IdCrates")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crates");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PaymentVendor", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Crates", "Crates")
                        .WithMany()
                        .HasForeignKey("IdCrates")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("IdVendor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crates");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PriceLists", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Product", "Product")
                        .WithMany("PriceLists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Product", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("InventoryManagement.Data.Models.Marque", "Marque")
                        .WithMany()
                        .HasForeignKey("MarqueId");

                    b.HasOne("InventoryManagement.Data.Models.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId");

                    b.HasOne("InventoryManagement.Data.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Category");

                    b.Navigation("Marque");

                    b.Navigation("Nature");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Purchase", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Crates", "Crates")
                        .WithMany()
                        .HasForeignKey("IdCrates");

                    b.HasOne("InventoryManagement.Data.Models.Vendor", "Vendor")
                        .WithMany("Purchases")
                        .HasForeignKey("IdVendor");

                    b.Navigation("Crates");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.PurchaseLine", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Models.Purchase", "Purchase")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("IdPurchase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnPurchase", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Crates", "Crates")
                        .WithMany()
                        .HasForeignKey("IdCrates");

                    b.HasOne("InventoryManagement.Data.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("IdVendor");

                    b.Navigation("Crates");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnPurchaseLine", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.ReturnPurchase", "ReturnPurchase")
                        .WithMany("ReturnPurchaseLine")
                        .HasForeignKey("IdReturnSales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnPurchase");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnSales", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Crates", "Crates")
                        .WithMany()
                        .HasForeignKey("IdCrates");

                    b.HasOne("InventoryManagement.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer");

                    b.Navigation("Crates");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnSalesLine", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.ReturnSales", "ReturnSales")
                        .WithMany("ReturnSalesLine")
                        .HasForeignKey("IdReturnSales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnSales");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.SalesInvoiceLine", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Data.Models.SalesInvoices", "SalesInvoice")
                        .WithMany("salesInvoiceLines")
                        .HasForeignKey("IdSalesInvoice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.SalesInvoices", b =>
                {
                    b.HasOne("InventoryManagement.Data.Models.Crates", "Crates")
                        .WithMany()
                        .HasForeignKey("IdCrates");

                    b.HasOne("InventoryManagement.Data.Models.Customer", "Customer")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("IdCustomer");

                    b.Navigation("Crates");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Customer", b =>
                {
                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Product", b =>
                {
                    b.Navigation("PriceLists");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseLines");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnPurchase", b =>
                {
                    b.Navigation("ReturnPurchaseLine");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.ReturnSales", b =>
                {
                    b.Navigation("ReturnSalesLine");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.SalesInvoices", b =>
                {
                    b.Navigation("salesInvoiceLines");
                });

            modelBuilder.Entity("InventoryManagement.Data.Models.Vendor", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
